workflows:
  react-native-android-minimal-apk:
    name: React Native Android APK Build
    max_build_duration: 60
    environment:
      vars:
        WORKING_DIRECTORY: "coin-box"
      node: latest
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $WORKING_DIRECTORY/node_modules
    scripts:
      - name: Install dependencies
        script: |
          cd "$WORKING_DIRECTORY"
          npm install --no-audit --no-fund

      - name: Expo prebuild (android)
        script: |
          cd "$WORKING_DIRECTORY"
          rm -rf android
          npx expo prebuild --platform android --clean

      - name: Criar proguard-rules.pro CORRETO para WebView
        script: |
          cd "$WORKING_DIRECTORY"
          cat > android/app/proguard-rules.pro << 'EOF'
-keep class com.facebook.react.** { *; }
-keep class com.facebook.hermes.** { *; }
-keep class expo.modules.** { *; }
-keep class com.nexa.cbox.** { *; }
-keep class com.reactnativecommunity.webview.** { *; }
-keep class android.webkit.** { *; }
-keep class com.th3rdwave.safeareacontext.** { *; }
-keep class com.swmansion.** { *; }

-dontwarn com.facebook.**
-dontwarn okhttp3.**
-dontwarn okio.**

-keepattributes *Annotation*
-keepattributes JavascriptInterface

-optimizationpasses 2
-dontpreverify
EOF

      - name: Modificar build.gradle para otimização SEGURA
        script: |
          cd "$WORKING_DIRECTORY/android/app"
          
          # Backup
          cp build.gradle build.gradle.backup
          
          # Adicionar buildTypes com minify DESABILITADO temporariamente
          sed -i.bak '/buildTypes {/,/}/ {
            /release {/,/}/ {
              s/minifyEnabled true/minifyEnabled false/
              s/shrinkResources true/shrinkResources false/
            }
          }' build.gradle || true
          
          # Se não funcionou, força manualmente
          cat build.gradle | grep -q "minifyEnabled false" || {
            sed -i.bak '/release {/a\
            \            minifyEnabled false\
            \            shrinkResources false\
            \            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
            ' build.gradle
          }
          
          echo "=== build.gradle release config ==="
          grep -A 10 "release {" build.gradle

      - name: Build APK SEM minify (para testar)
        script: |
          cd "$WORKING_DIRECTORY/android"
          chmod +x ./gradlew
          ./gradlew clean
          ./gradlew assembleRelease --no-daemon -Dorg.gradle.jvmargs="-Xmx4096m" --stacktrace 2>&1 | tee /tmp/build.log
          
          if [ ${PIPESTATUS[0]} -ne 0 ]; then
            echo "=== ERRO COMPLETO ==="
            tail -200 /tmp/build.log
            exit 1
          fi

      - name: Verificar tamanho e copiar APK
        script: |
          cd "$WORKING_DIRECTORY"
          echo "==> APKs gerados:"
          ls -lh android/app/build/outputs/apk/release/*.apk
          
          APK_PATH=$(find android/app/build/outputs/apk/release -name "*.apk" -type f | head -1)
          if [ -z "$APK_PATH" ]; then
            echo "Erro: Nenhum APK encontrado!"
            exit 1
          fi
          
          mkdir -p "$CM_BUILD_DIR"
          cp "$APK_PATH" "$CM_BUILD_DIR/app-release.apk"
          
          echo "==> Tamanho final do APK:"
          du -h "$CM_BUILD_DIR/app-release.apk"

    artifacts:
      - $CM_BUILD_DIR/*.apk
    publishing:
      email:
        recipients:
          - seu-email@example.com
        notify:
          success: true
          failure: true