workflows:
  react-native-android-minimal-apk:
    name: React Native Android APK Build
    max_build_duration: 60
    environment:
      vars:
        WORKING_DIRECTORY: "coin-box"
      node: latest
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $WORKING_DIRECTORY/node_modules
    scripts:
      - name: Install dependencies
        script: |
          cd "$WORKING_DIRECTORY"
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install --no-audit --no-fund
          fi

      - name: Expo prebuild (android)
        script: |
          cd "$WORKING_DIRECTORY"
          rm -rf android
          npx expo prebuild --platform android --clean

      - name: Create ProGuard and gradle.properties
        script: |
          APP_DIR="$PWD/$WORKING_DIRECTORY/android/app"
          GRADLE_PROPS="$PWD/$WORKING_DIRECTORY/android/gradle.properties"
          
          mkdir -p "$APP_DIR"
          
          cat > "$APP_DIR/proguard-rules.pro" <<'PROGUARD_EOF'
          -keep class com.facebook.react.** { *; }
          -keep class com.facebook.hermes.** { *; }
          -dontwarn com.facebook.react.**
          -dontwarn okhttp3.**
          -dontwarn okio.**
          -keepclassmembers class * { @com.facebook.react.uimanager.annotations.ReactProp *; }
          PROGUARD_EOF
          
          if [ -f "$GRADLE_PROPS" ]; then
            grep -q "^org.gradle.jvmargs" "$GRADLE_PROPS" || echo "org.gradle.jvmargs=-Xmx4608m" >> "$GRADLE_PROPS"
            grep -q "^android.enableR8" "$GRADLE_PROPS" || echo "android.enableR8=true" >> "$GRADLE_PROPS"
          else
            echo "org.gradle.jvmargs=-Xmx4608m" > "$GRADLE_PROPS"
            echo "android.enableR8=true" >> "$GRADLE_PROPS"
          fi

      - name: Build RELEASE APK
        script: |
          cd "$WORKING_DIRECTORY/android"
          chmod +x ./gradlew
          ./gradlew clean assembleRelease --no-daemon
          
          APKS=$(find app/build/outputs -type f -name "*.apk")
          if [ -z "$APKS" ]; then
            echo "No APK built"
            exit 1
          fi
          
          SMALLEST_APK=$(ls -lS app/build/outputs/apk/release/*.apk | tail -1 | awk '{print $NF}')
          cp "$SMALLEST_APK" "$CM_BUILD_DIR/app-release.apk"
          echo "APK copied to $CM_BUILD_DIR/app-release.apk"

    artifacts:
      - $CM_BUILD_DIR/*.apk
    publishing:
      email:
        recipients:
          - seu-email@example.com
        notify:
          success: true
          failure: true