workflows:
  android-release:
    name: Android Release
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      
      - name: Otimizar assets (comprimir imagens)
        script: |
          # Comprimir PNGs se existirem
          find . -name "*.png" -exec optipng -o7 {} \; || true
          # Comprimir JPGs se existirem  
          find . -name "*.jpg" -o -name "*.jpeg" | xargs jpegoptim --max=85 --strip-all || true
      
      - name: Build APK otimizado (arm64 only + ProGuard + shrink)
        script: |
          flutter build apk \
            --release \
            --target-platform android-arm64 \
            --obfuscate \
            --split-debug-info=build/app/outputs/symbols \
            --shrink \
            --tree-shake-icons
      
      - name: Verificar tamanho do APK
        script: |
          ls -lh build/app/outputs/flutter-apk/
          echo "Tamanho do APK:"
          du -h build/app/outputs/flutter-apk/*.apk
    
    artifacts:
      - build/app/outputs/flutter-apk/*.apk