workflows:
  android-build:
    name: Android APK
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        WORKING_DIRECTORY: "coin-box"
      node: 20.11.0
      java: 17
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $WORKING_DIRECTORY/node_modules
    scripts:
      - name: Install dependencies
        script: |
          cd "$WORKING_DIRECTORY"
          npm install

      - name: Expo prebuild
        script: |
          cd "$WORKING_DIRECTORY"
          rm -rf android
          npx expo prebuild --platform android --clean

      - name: Configure build
        script: |
          cd "$WORKING_DIRECTORY/android"
          
          # Configurar gradle.properties
          echo "" >> gradle.properties
          echo "org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=1g" >> gradle.properties
          echo "org.gradle.parallel=true" >> gradle.properties
          echo "org.gradle.daemon=false" >> gradle.properties
          echo "android.enableJetifier=true" >> gradle.properties
          echo "android.useAndroidX=true" >> gradle.properties
          echo "reactNativeArchitectures=arm64-v8a" >> gradle.properties
          
          # Desabilitar minify no build.gradle
          cd app
          sed -i.bak 's/minifyEnabled true/minifyEnabled false/' build.gradle
          sed -i.bak 's/shrinkResources true/shrinkResources false/' build.gradle
          
          echo "=== Config aplicada ==="
          grep -A 5 "minifyEnabled" build.gradle

      - name: Build APK
        script: |
          set -e
          set -x
          
          cd "$WORKING_DIRECTORY/android"
          
          echo "=========================================="
          echo "INICIANDO BUILD"
          echo "=========================================="
          pwd
          
          echo ""
          echo "=========================================="
          echo "BUILDANDO APK RELEASE"
          echo "=========================================="
          ./gradlew assembleRelease \
            --no-daemon \
            --stacktrace \
            --warning-mode all 2>&1 | tee /tmp/build.log
          
          BUILD_EXIT=${PIPESTATUS[0]}
          
          echo ""
          echo "=========================================="
          echo "BUILD EXIT CODE: $BUILD_EXIT"
          echo "=========================================="
          
          if [ $BUILD_EXIT -ne 0 ]; then
            echo ""
            echo "❌❌❌ BUILD FALHOU ❌❌❌"
            echo ""
            echo "=========================================="
            echo "PROCURANDO ERRO:"
            echo "=========================================="
            grep -B5 -A5 "BUILD FAILED\|FAILURE\|Error:\|Exception" /tmp/build.log | tail -200
            echo ""
            echo "=========================================="
            echo "LOG COMPLETO EM /tmp/build.log"
            echo "=========================================="
            exit 1
          fi
          
          echo ""
          echo "✅ BUILD CONCLUÍDO COM SUCESSO"

      - name: Copy APK
        script: |
          set -e
          set -x
          
          cd "$WORKING_DIRECTORY"
          
          echo "=========================================="
          echo "PROCURANDO APK"
          echo "=========================================="
          
          find android/app/build/outputs -name "*.apk" -type f
          
          APK_PATH=$(find android/app/build/outputs/apk/release -name "*.apk" -type f | head -1)
          
          if [ -z "$APK_PATH" ]; then
            echo ""
            echo "❌ NENHUM APK ENCONTRADO!"
            echo ""
            echo "Estrutura de build/outputs:"
            ls -R android/app/build/outputs/ || echo "Diretório não existe"
            exit 1
          fi
          
          echo ""
          echo "✅ APK encontrado: $APK_PATH"
          echo ""
          
          mkdir -p "$CM_BUILD_DIR"
          cp "$APK_PATH" "$CM_BUILD_DIR/coin-box.apk"
          
          echo "=========================================="
          echo "APK COPIADO"
          echo "=========================================="
          ls -lh "$CM_BUILD_DIR/coin-box.apk"
          echo ""
          echo "Tamanho: $(du -h "$CM_BUILD_DIR/coin-box.apk" | cut -f1)"

    artifacts:
      - $CM_BUILD_DIR/*.apk
      
    publishing:
      email:
        recipients:
          - alfredoooh.x3@gmail.com
        notify:
          success: true
          failure: true
