format_version: "1.0.0"

app:
  envs:
    - WORKING_DIRECTORY: "coin-box"

workflows:
  react-native-android-minimal-apk:
    max_build_duration: 60
    steps:
      - git-clone: {}
      - cache-pull: {}

      - script:
          title: Install dependencies
          inputs:
            - content: |
                #!/bin/bash
                set -euo pipefail
                echo "==> Install node deps"
                cd "$WORKING_DIRECTORY"
                if [ -f package-lock.json ]; then
                  npm ci
                else
                  npm install --no-audit --no-fund
                fi

      - script:
          title: Expo prebuild (android)
          inputs:
            - content: |
                #!/bin/bash
                set -euo pipefail
                echo "==> Expo prebuild (android) - clean"
                cd "$WORKING_DIRECTORY"
                rm -rf android
                npx expo prebuild --platform android --clean

      - script:
          title: Create ProGuard and gradle.properties (safe)
          inputs:
            - content: |
                #!/bin/bash
                set -euo pipefail
                echo "==> Writing proguard-rules.pro and gradle.properties tweaks (safe)"
                APP_DIR="$PWD/$WORKING_DIRECTORY/android/app"
                GRADLE_PROPS="$PWD/$WORKING_DIRECTORY/android/gradle.properties"

                mkdir -p "$APP_DIR"

                # Create minimal proguard rules
                cat > "$APP_DIR/proguard-rules.pro" <<'PROGUARD_EOF'
                -keep class com.facebook.react.** { *; }
                -keep class com.facebook.hermes.** { *; }
                -dontwarn com.facebook.react.**
                -dontwarn okhttp3.**
                -dontwarn okio.**
                -keepclassmembers class * { @com.facebook.react.uimanager.annotations.ReactProp *; }
                PROGUARD_EOF

                # Append gradle.properties entries only if missing
                if [ -f "$GRADLE_PROPS" ]; then
                  if ! grep -q "^org.gradle.jvmargs" "$GRADLE_PROPS"; then
                    echo "org.gradle.jvmargs=-Xmx4608m" >> "$GRADLE_PROPS"
                  fi
                  if ! grep -q "^android.enableR8" "$GRADLE_PROPS"; then
                    echo "android.enableR8=true" >> "$GRADLE_PROPS"
                  fi
                else
                  # create file if missing
                  echo "org.gradle.jvmargs=-Xmx4608m" > "$GRADLE_PROPS"
                  echo "android.enableR8=true" >> "$GRADLE_PROPS"
                fi

                echo "Created proguard-rules.pro and updated gradle.properties (safe)."

      - script:
          title: Build RELEASE APK (only)
          inputs:
            - content: |
                #!/bin/bash
                set -euo pipefail
                echo "==> Building release APK (assembleRelease)"
                cd "$WORKING_DIRECTORY/android"
                chmod +x ./gradlew || true
                ./gradlew clean
                ./gradlew assembleRelease --no-daemon

                echo "==> Locating generated APKs..."
                APKS=$(find app/build/outputs -type f -name "*.apk" 2>/dev/null || true)
                if [ -z "$APKS" ]; then
                  echo "No APK built — check gradle output above."
                  exit 1
                fi

                # pick smallest APK built
                SMALLEST_APK=$(for f in $APKS; do printf "%s:%s\n" "$(stat -c%s "$f")" "$f"; done | sort -n | head -n1 | cut -d: -f2-)
                mkdir -p "$BITRISE_DEPLOY_DIR"
                cp "$SMALLEST_APK" "$BITRISE_DEPLOY_DIR/app-release.apk"

                echo "Final APK copied to $BITRISE_DEPLOY_DIR/app-release.apk"
                stat -c "APK size: %s bytes (%s KB)" "$BITRISE_DEPLOY_DIR/app-release.apk"

      - cache-push: {}
      - deploy-to-bitrise-io: {}