workflows:
  react-native-android-minimal-apk:
    name: React Native Android APK Build
    max_build_duration: 60
    environment:
      vars:
        WORKING_DIRECTORY: "coin-box"
      node: latest
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $WORKING_DIRECTORY/node_modules
    scripts:
      - name: Install dependencies
        script: |
          cd "$WORKING_DIRECTORY"
          npm install --no-audit --no-fund

      - name: Expo prebuild (android)
        script: |
          cd "$WORKING_DIRECTORY"
          rm -rf android
          npx expo prebuild --platform android --clean

      - name: Configure build for size optimization
        script: |
          APP_DIR="$PWD/$WORKING_DIRECTORY/android/app"
          GRADLE_PROPS="$PWD/$WORKING_DIRECTORY/android/gradle.properties"
          BUILD_GRADLE="$APP_DIR/build.gradle"
          
          mkdir -p "$APP_DIR"
          
          # ProGuard rules agressivo
          cat > "$APP_DIR/proguard-rules.pro" <<'PROGUARD_EOF'
          -keep class com.facebook.react.** { *; }
          -keep class com.facebook.hermes.** { *; }
          -dontwarn com.facebook.react.**
          -dontwarn okhttp3.**
          -dontwarn okio.**
          -keepclassmembers class * { @com.facebook.react.uimanager.annotations.ReactProp *; }
          -dontoptimize
          -dontobfuscate
          PROGUARD_EOF
          
          # gradle.properties otimizado
          cat > "$GRADLE_PROPS" <<'GRADLE_EOF'
          org.gradle.jvmargs=-Xmx4608m -XX:MaxMetaspaceSize=512m
          org.gradle.daemon=false
          org.gradle.configureondemand=true
          org.gradle.parallel=true
          android.enableR8=true
          android.enableR8.fullMode=true
          android.enableDexingArtifactTransform=true
          android.enableBuildCache=true
          android.useAndroidX=true
          android.enableJetifier=true
          GRADLE_EOF
          
          # Configurar splits de ABI no build.gradle
          if [ -f "$BUILD_GRADLE" ]; then
            # Adicionar splits se não existir
            if ! grep -q "splits {" "$BUILD_GRADLE"; then
              sed -i '/android {/a\
              \    splits {\
              \        abi {\
              \            enable true\
              \            reset()\
              \            include "armeabi-v7a", "arm64-v8a"\
              \            universalApk false\
              \        }\
              \    }' "$BUILD_GRADLE"
            fi
          fi

      - name: Build RELEASE APK
        script: |
          cd "$WORKING_DIRECTORY/android"
          chmod +x ./gradlew
          ./gradlew clean assembleRelease --no-daemon
          
          APKS=$(find app/build/outputs -type f -name "*.apk")
          if [ -z "$APKS" ]; then
            echo "No APK built"
            exit 1
          fi
          
          SMALLEST_APK=$(ls -lS app/build/outputs/apk/release/*.apk | tail -1 | awk '{print $NF}')
          cp "$SMALLEST_APK" "$CM_BUILD_DIR/app-release.apk"
          echo "APK copied to $CM_BUILD_DIR/app-release.apk"

    artifacts:
      - $CM_BUILD_DIR/*.apk
    publishing:
      email:
        recipients:
          - seu-email@example.com
        notify:
          success: true
          failure: true