workflows:
  react-native-android-fixed:
    name: React Native Android - CORRIGIDO DEFINITIVO
    max_build_duration: 60
    environment:
      vars:
        WORKING_DIRECTORY: "coin-box"
      node: latest
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $WORKING_DIRECTORY/node_modules
    scripts:
      - name: Install dependencies
        script: |
          cd "$WORKING_DIRECTORY"
          npm install --no-audit --no-fund
          npm install --save-dev @react-native-community/cli@latest --no-audit

      - name: Expo prebuild (android)
        script: |
          cd "$WORKING_DIRECTORY"
          rm -rf android
          npx expo prebuild --platform android --clean

      - name: Substituir build.gradle
        script: |
          cd "$WORKING_DIRECTORY"
          cat > android/app/build.gradle <<'EOFGRADLE'
          apply plugin: "com.android.application"
          apply plugin: "org.jetbrains.kotlin.android"
          apply plugin: "com.facebook.react"

          def projectRoot = rootDir.getAbsoluteFile().getParentFile().getAbsolutePath()

          react {
              def entryFileScript = ["node", "-e", "require('expo/scripts/resolveAppEntry')", projectRoot, "android", "absolute"].execute(null, rootDir)
              entryFileScript.waitFor()
              if (entryFileScript.exitValue() == 0) {
                  entryFile = file(entryFileScript.text.trim())
              } else {
                  entryFile = file("$projectRoot/index.js")
              }
              
              reactNativeDir = new File(["node", "--print", "require.resolve('react-native/package.json')"].execute(null, rootDir).text.trim()).getParentFile().getAbsoluteFile()
              hermesCommand = new File(["node", "--print", "require.resolve('react-native/package.json')"].execute(null, rootDir).text.trim()).getParentFile().getAbsolutePath() + "/sdks/hermesc/%OS-BIN%/hermesc"
              codegenDir = new File(["node", "--print", "require.resolve('@react-native/codegen/package.json', { paths: [require.resolve('react-native/package.json')] })"].execute(null, rootDir).text.trim()).getParentFile().getAbsoluteFile()
              
              enableBundleCompression = false
              bundleCommand = "export:embed"
              bundleAssetName = "index.android.bundle"
              
              cliFile = new File(["node", "--print", "require.resolve('@expo/cli', { paths: [require.resolve('expo/package.json')] })"].execute(null, rootDir).text.trim())
              autolinkLibrariesWithApp()
          }

          android {
              ndkVersion rootProject.ext.ndkVersion
              buildToolsVersion rootProject.ext.buildToolsVersion
              compileSdk rootProject.ext.compileSdkVersion
              namespace "com.nexa.cbox"

              defaultConfig {
                  applicationId "com.nexa.cbox"
                  minSdk 24
                  targetSdk rootProject.ext.targetSdkVersion
                  versionCode 1
                  versionName "1.0"
                  buildConfigField("boolean", "IS_NEW_ARCHITECTURE_ENABLED", "false")
                  multiDexEnabled true
              }

              signingConfigs {
                  debug {
                      storeFile file('debug.keystore')
                      storePassword 'android'
                      keyAlias 'androiddebugkey'
                      keyPassword 'android'
                  }
              }

              buildTypes {
                  release {
                      signingConfig signingConfigs.debug
                      minifyEnabled false
                      shrinkResources false
                      crunchPngs false
                      zipAlignEnabled true
                      debuggable true
                      jniDebuggable true
                  }
              }
              
              splits {
                  abi {
                      enable true
                      reset()
                      include 'arm64-v8a'
                      universalApk false
                  }
              }

              packagingOptions {
                  jniLibs {
                      useLegacyPackaging false
                  }
                  resources {
                      excludes += [
                          'META-INF/DEPENDENCIES',
                          'META-INF/LICENSE',
                          'META-INF/LICENSE.txt',
                          'META-INF/license.txt',
                          'META-INF/NOTICE',
                          'META-INF/NOTICE.txt',
                          'META-INF/notice.txt',
                          'META-INF/ASL2.0',
                          '**/kotlin/**',
                          '**/*.kotlin_module'
                      ]
                  }
                  pickFirst 'lib/*/libc++_shared.so'
                  pickFirst 'lib/*/libfbjni.so'
                  pickFirst 'lib/*/libjsi.so'
              }
              
              compileOptions {
                  sourceCompatibility JavaVersion.VERSION_17
                  targetCompatibility JavaVersion.VERSION_17
              }
              
              kotlinOptions {
                  jvmTarget = '17'
              }
          }

          dependencies {
              implementation("com.facebook.react:react-android")
              implementation("com.facebook.react:hermes-android")
              implementation("androidx.appcompat:appcompat:1.6.1")
              implementation("androidx.swiperefreshlayout:swiperefreshlayout:1.1.0")
              implementation("androidx.multidex:multidex:2.0.1")
          }
          EOFGRADLE

      - name: Corrigir MainApplication.kt - SEM LOAD()
        script: |
          cd "$WORKING_DIRECTORY"
          cat > android/app/src/main/java/com/nexa/cbox/MainApplication.kt <<'EOFKOTLIN'
          package com.nexa.cbox
          
          import android.app.Application
          import android.content.res.Configuration
          import android.util.Log
          import expo.modules.ApplicationLifecycleDispatcher
          import expo.modules.ReactNativeHostWrapper
          import com.facebook.react.PackageList
          import com.facebook.react.ReactApplication
          import com.facebook.react.ReactNativeHost
          import com.facebook.react.ReactPackage
          import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.load
          import com.facebook.react.defaults.DefaultReactNativeHost
          import com.facebook.soloader.SoLoader
          
          class MainApplication : Application(), ReactApplication {
            override val reactNativeHost: ReactNativeHost = ReactNativeHostWrapper(
              this,
              object : DefaultReactNativeHost(this) {
                override fun getPackages(): List<ReactPackage> {
                  val packages = PackageList(this).packages
                  Log.d("CoinBox", "✅ Loaded ${packages.size} packages")
                  return packages
                }
          
                override fun getJSMainModuleName(): String {
                  Log.d("CoinBox", "✅ JS Module: .expo/.virtual-metro-entry")
                  return ".expo/.virtual-metro-entry"
                }
          
                override fun getUseDeveloperSupport(): Boolean = false
          
                override val isNewArchEnabled: Boolean = false
                override val isHermesEnabled: Boolean = true
                
                override fun getBundleAssetName(): String {
                  Log.d("CoinBox", "✅ Bundle: index.android.bundle")
                  return "index.android.bundle"
                }
              }
            )
          
            override fun onCreate() {
              super.onCreate()
              Log.d("CoinBox", "🚀 === APP INICIANDO ===")
              
              try {
                SoLoader.init(this, false)
                Log.d("CoinBox", "✅ SoLoader inicializado")
                
                // 🔥 CORREÇÃO CRÍTICA: SÓ CARREGA SE NEW ARCH ESTIVER ATIVADA
                if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
                  load()
                  Log.d("CoinBox", "✅ New Architecture carregada")
                } else {
                  Log.d("CoinBox", "ℹ️ New Architecture desabilitada (normal)")
                }
                
                ApplicationLifecycleDispatcher.onApplicationCreate(this)
                Log.d("CoinBox", "✅ Lifecycle dispatcher inicializado")
                
                Log.d("CoinBox", "🎉 === APP INICIADO COM SUCESSO ===")
              } catch (e: Exception) {
                Log.e("CoinBox", "❌ ERRO FATAL durante inicialização", e)
                e.printStackTrace()
                // NÃO fazer throw - deixar o erro ser mostrado mas não crashar imediatamente
              }
            }
          
            override fun onConfigurationChanged(newConfig: Configuration) {
              super.onConfigurationChanged(newConfig)
              ApplicationLifecycleDispatcher.onConfigurationChanged(this, newConfig)
            }
          }
          EOFKOTLIN

      - name: Corrigir MainActivity.kt
        script: |
          cd "$WORKING_DIRECTORY"
          cat > android/app/src/main/java/com/nexa/cbox/MainActivity.kt <<'EOFKOTLIN'
          package com.nexa.cbox
          
          import android.os.Build
          import android.os.Bundle
          import android.util.Log
          import com.facebook.react.ReactActivity
          import com.facebook.react.ReactActivityDelegate
          import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.fabricEnabled
          import com.facebook.react.defaults.DefaultReactActivityDelegate
          import expo.modules.ReactActivityDelegateWrapper
          
          class MainActivity : ReactActivity() {
          
            override fun onCreate(savedInstanceState: Bundle?) {
              Log.d("CoinBox", "🏁 MainActivity INICIANDO")
              setTheme(R.style.AppTheme)
              super.onCreate(savedInstanceState)
              Log.d("CoinBox", "✅ MainActivity CRIADA")
            }
          
            override fun getMainComponentName(): String {
              Log.d("CoinBox", "📱 Main component: main")
              return "main"
            }
          
            override fun createReactActivityDelegate(): ReactActivityDelegate {
              return ReactActivityDelegateWrapper(
                this,
                BuildConfig.IS_NEW_ARCHITECTURE_ENABLED,
                object : DefaultReactActivityDelegate(
                  this,
                  mainComponentName,
                  fabricEnabled
                ) {}
              )
            }
          
            override fun invokeDefaultOnBackPressed() {
              if (Build.VERSION.SDK_INT <= Build.VERSION_CODES.R) {
                if (!moveTaskToBack(false)) {
                  super.invokeDefaultOnBackPressed()
                }
                return
              }
              super.invokeDefaultOnBackPressed()
            }
          }
          EOFKOTLIN

      - name: Verificar dependências críticas
        script: |
          cd "$WORKING_DIRECTORY"
          echo "🔍 === VERIFICANDO DEPENDÊNCIAS ==="
          
          echo "📦 React Native:"
          node -p "require('./node_modules/react-native/package.json').version"
          
          echo "📦 Expo:"
          node -p "require('./node_modules/expo/package.json').version"
          
          echo "📦 React:"
          node -p "require('./node_modules/react/package.json').version"
          
          echo ""
          echo "📱 Verificando módulos nativos críticos:"
          ls -la node_modules/react-native-reanimated 2>/dev/null && echo "✅ reanimated" || echo "❌ reanimated"
          ls -la node_modules/react-native-gesture-handler 2>/dev/null && echo "✅ gesture-handler" || echo "❌ gesture-handler"
          ls -la node_modules/react-native-screens 2>/dev/null && echo "✅ screens" || echo "❌ screens"

      - name: Testar bundle ANTES do build
        script: |
          cd "$WORKING_DIRECTORY"
          echo "🧪 === TESTANDO BUNDLE JAVASCRIPT ==="
          
          mkdir -p /tmp/test-bundle
          
          npx expo export:embed \
            --platform android \
            --bundle-output /tmp/test-bundle/index.android.bundle \
            --assets-dest /tmp/test-bundle \
            --dev false \
            --minify false
          
          if [ $? -eq 0 ]; then
            echo "✅ Bundle criado com sucesso!"
            echo "📦 Tamanho do bundle:"
            du -h /tmp/test-bundle/index.android.bundle
            
            # Verificar se não está vazio
            if [ -s /tmp/test-bundle/index.android.bundle ]; then
              echo "✅ Bundle contém código"
            else
              echo "❌ ERRO: Bundle está vazio!"
              exit 1
            fi
          else
            echo "❌ ERRO ao criar bundle!"
            exit 1
          fi

      - name: Build APK
        script: |
          cd "$WORKING_DIRECTORY/android"
          chmod +x ./gradlew
          echo "🧹 Limpando build anterior..."
          ./gradlew clean
          
          echo "🔨 Compilando APK..."
          ./gradlew assembleRelease --stacktrace --info

      - name: Verificar e copiar APK
        script: |
          cd "$WORKING_DIRECTORY"
          echo "==> APKs gerados:"
          find android/app/build/outputs/apk -name "*.apk" -type f -exec ls -lh {} \;
          
          APK_PATH=$(find android/app/build/outputs/apk/release -name "*arm64-v8a-release.apk" -type f | head -1)
          if [ -z "$APK_PATH" ]; then
            APK_PATH=$(find android/app/build/outputs/apk/release -name "*.apk" -type f | head -1)
          fi
          
          if [ -z "$APK_PATH" ]; then
            echo "❌ Erro: Nenhum APK encontrado!"
            exit 1
          fi
          
          echo ""
          echo "📦 Conteúdo do APK:"
          unzip -l "$APK_PATH" | grep -E "(index.android.bundle|assets|\.so$)" | head -30
          
          mkdir -p "$CM_BUILD_DIR"
          cp "$APK_PATH" "$CM_BUILD_DIR/CoinBox-v1.0.apk"
          
          echo ""
          echo "==> ✅ APK FINAL:"
          ls -lh "$CM_BUILD_DIR/CoinBox-v1.0.apk"
          echo ""
          echo "🎉 BUILD CONCLUÍDO COM SUCESSO!"

    artifacts:
      - $CM_BUILD_DIR/*.apk
    publishing:
      email:
        recipients:
          - seu-email@example.com
        notify:
          success: true
          failure: true