workflows:
  android-build:
    name: Android APK
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        WORKING_DIRECTORY: "coin-box"
      node: 20.11.0
      java: 17
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $WORKING_DIRECTORY/node_modules
    scripts:
      - name: Install dependencies
        script: |
          cd "$WORKING_DIRECTORY"
          npm install

      - name: Expo prebuild
        script: |
          cd "$WORKING_DIRECTORY"
          rm -rf android
          npx expo prebuild --platform android --clean

      - name: Configure build
        script: |
          cd "$WORKING_DIRECTORY/android"
          
          # Configurar gradle.properties
          echo "" >> gradle.properties
          echo "org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=1g" >> gradle.properties
          echo "org.gradle.parallel=true" >> gradle.properties
          echo "org.gradle.daemon=false" >> gradle.properties
          echo "android.enableJetifier=true" >> gradle.properties
          echo "android.useAndroidX=true" >> gradle.properties
          echo "reactNativeArchitectures=arm64-v8a" >> gradle.properties
          
          # Configurar build.gradle do app para usar assinatura debug
          cd app
          
          # Adicionar signingConfig debug no release
          cat > /tmp/fix_build.sh << 'FIXSCRIPT'
          #!/bin/bash
          
          # Desabilitar minify
          sed -i.bak 's/minifyEnabled true/minifyEnabled false/g' build.gradle
          sed -i.bak 's/shrinkResources true/shrinkResources false/g' build.gradle
          
          # Adicionar signingConfig se não existir
          if ! grep -q "signingConfig signingConfigs.debug" build.gradle; then
            sed -i.bak '/release {/a\
                signingConfig signingConfigs.debug
          ' build.gradle
          fi
          
          echo "✓ build.gradle configurado"
          FIXSCRIPT
          
          chmod +x /tmp/fix_build.sh
          /tmp/fix_build.sh
          
          echo "=== Release config ==="
          grep -A 10 "release {" build.gradle

      - name: Build APK
        script: |
          set -e
          
          cd "$WORKING_DIRECTORY/android"
          
          echo "🚀 Iniciando build..."
          
          # Build SEM verbose - só mostrar erros
          ./gradlew assembleRelease \
            --no-daemon \
            --quiet \
            --warning-mode none 2>&1 | tee /tmp/build.log
          
          BUILD_EXIT=${PIPESTATUS[0]}
          
          if [ $BUILD_EXIT -ne 0 ]; then
            echo ""
            echo "❌ BUILD FALHOU!"
            echo ""
            echo "=== ERRO ==="
            cat /tmp/build.log
            echo ""
            exit 1
          fi
          
          echo "✅ Build completo!"

      - name: Copy APK
        script: |
          set -e
          set -x
          
          cd "$WORKING_DIRECTORY"
          
          echo "=========================================="
          echo "PROCURANDO APK"
          echo "=========================================="
          
          find android/app/build/outputs -name "*.apk" -type f
          
          APK_PATH=$(find android/app/build/outputs/apk/release -name "*.apk" -type f | head -1)
          
          if [ -z "$APK_PATH" ]; then
            echo ""
            echo "❌ NENHUM APK ENCONTRADO!"
            echo ""
            echo "Estrutura de build/outputs:"
            ls -R android/app/build/outputs/ || echo "Diretório não existe"
            exit 1
          fi
          
          echo ""
          echo "✅ APK encontrado: $APK_PATH"
          echo ""
          
          mkdir -p "$CM_BUILD_DIR"
          cp "$APK_PATH" "$CM_BUILD_DIR/coin-box.apk"
          
          echo "=========================================="
          echo "APK COPIADO"
          echo "=========================================="
          ls -lh "$CM_BUILD_DIR/coin-box.apk"
          echo ""
          echo "Tamanho: $(du -h "$CM_BUILD_DIR/coin-box.apk" | cut -f1)"

    artifacts:
      - $CM_BUILD_DIR/*.apk
      
    publishing:
      email:
        recipients:
          - alfredoooh.x3@gmail.com
        notify:
          success: true
          failure: true
