workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 60
    environment:
      node: latest
      java: 17
      vars:
        WORKING_DIRECTORY: "coin-box"
    scripts:
      - name: Install dependencies
        script: |
          cd $WORKING_DIRECTORY
          npm install
      
      - name: Otimizar imagens
        script: |
          cd $WORKING_DIRECTORY
          find assets -name "*.png" -exec optipng -o7 {} \; 2>/dev/null || true
          find assets -name "*.jpg" -o -name "*.jpeg" | xargs jpegoptim --max=75 --strip-all 2>/dev/null || true
      
      - name: Clean and prebuild Android
        script: |
          cd $WORKING_DIRECTORY
          rm -rf android
          npx expo prebuild --platform android --clean
      
      - name: Build APK OTIMIZADO
        script: |
          cd $WORKING_DIRECTORY/android
          ./gradlew assembleRelease \
            --no-daemon \
            -Pandroid.enableMinifyInReleaseBuilds=true \
            -Pandroid.enableShrinkResourcesInReleaseBuilds=true \
            -Pandroid.enablePngCrunchInReleaseBuilds=true \
            -Pandroid.enableR8.fullMode=true
      
      - name: Verificar tamanho
        script: |
          cd $WORKING_DIRECTORY
          ls -lh android/app/build/outputs/apk/release/*.apk
          du -h android/app/build/outputs/apk/release/*.apk
    
    artifacts:
      - coin-box/android/app/build/outputs/**/*.apk