workflows:
  android-build:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        WORKING_DIRECTORY: "coin-box"
      node: 20.11.0
      java: 17
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $WORKING_DIRECTORY/node_modules
    scripts:
      - name: Install
        script: |
          cd "$WORKING_DIRECTORY"
          npm install

      - name: Prebuild
        script: |
          cd "$WORKING_DIRECTORY"
          rm -rf android
          npx expo prebuild --platform android --clean

      - name: Build
        script: |
          cd "$WORKING_DIRECTORY"
          
          mkdir -p "$CM_BUILD_DIR"
          cp codemagic.yaml "$CM_BUILD_DIR/codemagic.yaml.txt"
          
          cd android
          ./gradlew assembleRelease --no-daemon 2>&1 | tee /tmp/build.log
          
          if [ ${PIPESTATUS[0]} -ne 0 ]; then
            echo "BUILD FAILED"
            
            grep -B5 -A5 "FAILURE\|Error:" /tmp/build.log | head -40 > "$CM_BUILD_DIR/error.txt"
            cp "$WORKING_DIRECTORY/babel.config.js" "$CM_BUILD_DIR/babel.txt"
            cp "$WORKING_DIRECTORY/android/app/build.gradle" "$CM_BUILD_DIR/build-gradle.txt"
            cp "$WORKING_DIRECTORY/package.json" "$CM_BUILD_DIR/package.txt"
            
            exit 1
          fi

      - name: Copy APK
        script: |
          cd "$WORKING_DIRECTORY"
          APK=$(find android/app/build/outputs/apk/release -name "*.apk" | head -1)
          
          if [ -n "$APK" ]; then
            cp "$APK" "$CM_BUILD_DIR/coin-box.apk"
          fi

    artifacts:
      - $CM_BUILD_DIR/*
      
    publishing:
      email:
        recipients:
          - alfredoooh.x3@gmail.com
        notify:
          success: true
          failure: true
