workflows:
  expo-android-webview:
    name: Expo Android WebView
    max_build_duration: 60
    environment:
      vars:
        WORKING_DIRECTORY: "coin-box"
      node: latest
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $WORKING_DIRECTORY/node_modules
    scripts:
      - name: Install dependencies
        script: |
          cd "$WORKING_DIRECTORY"
          npm install

      - name: Expo prebuild
        script: |
          cd "$WORKING_DIRECTORY"
          rm -rf android ios
          npx expo prebuild --platform android --clean

      - name: Build APK
        script: |
          cd "$WORKING_DIRECTORY/android"
          chmod +x ./gradlew
          ./gradlew assembleRelease --no-daemon

      - name: Copy APK
        script: |
          cd "$WORKING_DIRECTORY"
          APK_PATH=$(find android/app/build/outputs/apk/release -name "*.apk" -type f | head -1)
          
          if [ -z "$APK_PATH" ]; then
            echo "❌ Erro: Nenhum APK encontrado!"
            exit 1
          fi
          
          mkdir -p "$CM_BUILD_DIR"
          cp "$APK_PATH" "$CM_BUILD_DIR/app-release.apk"
          
          echo "✅ APK copiado:"
          du -h "$CM_BUILD_DIR/app-release.apk"

    artifacts:
      - $CM_BUILD_DIR/*.apk
    publishing:
      email:
        recipients:
          - seu-email@example.com
        notify:
          success: true
          failure: true