workflows:
  react-native-android-minimal-apk:
    name: React Native Android APK Build
    max_build_duration: 60
    environment:
      vars:
        WORKING_DIRECTORY: "coin-box"
      node: latest
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $WORKING_DIRECTORY/node_modules
    scripts:
      - name: Install dependencies
        script: |
          cd "$WORKING_DIRECTORY"
          npm install --no-audit --no-fund

      - name: Expo prebuild (android)
        script: |
          cd "$WORKING_DIRECTORY"
          rm -rf android
          npx expo prebuild --platform android --clean

      - name: Substituir build.gradle otimizado
        script: |
          cd "$WORKING_DIRECTORY"
          cat > android/app/build.gradle <<'EOFGRADLE'
          apply plugin: "com.android.application"
          apply plugin: "org.jetbrains.kotlin.android"
          apply plugin: "com.facebook.react"

          def projectRoot = rootDir.getAbsoluteFile().getParentFile().getAbsolutePath()

          react {
              entryFile = file(["node", "-e", "require('expo/scripts/resolveAppEntry')", projectRoot, "android", "absolute"].execute(null, rootDir).text.trim())
              reactNativeDir = new File(["node", "--print", "require.resolve('react-native/package.json')"].execute(null, rootDir).text.trim()).getParentFile().getAbsoluteFile()
              hermesCommand = new File(["node", "--print", "require.resolve('react-native/package.json')"].execute(null, rootDir).text.trim()).getParentFile().getAbsolutePath() + "/sdks/hermesc/%OS-BIN%/hermesc"
              codegenDir = new File(["node", "--print", "require.resolve('@react-native/codegen/package.json', { paths: [require.resolve('react-native/package.json')] })"].execute(null, rootDir).text.trim()).getParentFile().getAbsoluteFile()
              cliFile = new File(["node", "--print", "require.resolve('@expo/cli', { paths: [require.resolve('expo/package.json')] })"].execute(null, rootDir).text.trim())
              bundleCommand = "export"
              autolinkLibrariesWithApp()
          }

          android {
              ndkVersion rootProject.ext.ndkVersion
              buildToolsVersion rootProject.ext.buildToolsVersion
              compileSdk rootProject.ext.compileSdkVersion
              namespace "com.nexa.cbox"

              defaultConfig {
                  applicationId "com.nexa.cbox"
                  minSdk 24
                  targetSdk rootProject.ext.targetSdkVersion
                  versionCode 1
                  versionName "1.0"
                  buildConfigField("String", "REACT_NATIVE_RELEASE_LEVEL", "\"STABLE\"")
                  buildConfigField("boolean", "IS_NEW_ARCHITECTURE_ENABLED", "false")
              }

              signingConfigs {
                  debug {
                      storeFile file('debug.keystore')
                      storePassword 'android'
                      keyAlias 'androiddebugkey'
                      keyPassword 'android'
                  }
              }

              buildTypes {
                  release {
                      signingConfig signingConfigs.debug
                      minifyEnabled true
                      shrinkResources true
                      crunchPngs true
                      zipAlignEnabled true
                      debuggable false
                      jniDebuggable false
                      renderscriptDebuggable false
                      proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
                  }
              }
              
              splits {
                  abi {
                      enable true
                      reset()
                      include 'arm64-v8a'
                      universalApk false
                  }
                  density {
                      enable true
                      reset()
                      include 'xxhdpi'
                  }
              }
              
              bundle {
                  language {
                      enableSplit = true
                  }
                  density {
                      enableSplit = true
                  }
                  abi {
                      enableSplit = true
                  }
              }

              packagingOptions {
                  jniLibs {
                      useLegacyPackaging false
                  }
                  resources {
                      excludes += [
                          'META-INF/**',
                          '**/*.kotlin_module',
                          '**/*.version',
                          '**/*.properties',
                          'kotlin/**',
                          'DebugProbesKt.bin',
                          'okhttp3/internal/publicsuffix/publicsuffixes.gz'
                      ]
                  }
                  pickFirst 'lib/*/libc++_shared.so'
                  pickFirst 'lib/*/libfbjni.so'
                  pickFirst 'lib/*/libjsi.so'
              }
          }

          dependencies {
              implementation("com.facebook.react:react-android")
              implementation("com.facebook.react:hermes-android")
          }
          EOFGRADLE

      - name: Criar proguard-rules.pro
        script: |
          cd "$WORKING_DIRECTORY"
          cat > android/app/proguard-rules.pro <<'PROGUARDEOF'
          -keepattributes *Annotation*
          -keep class com.facebook.react.** { *; }
          -keep class com.facebook.hermes.** { *; }
          -keep class expo.modules.** { *; }
          -keep class com.nexa.cbox.** { *; }
          
          -dontwarn com.facebook.**
          -dontwarn okhttp3.**
          -dontwarn okio.**
          -dontwarn javax.annotation.**
          
          -assumenosideeffects class android.util.Log {
              public static *** d(...);
              public static *** v(...);
              public static *** i(...);
              public static *** w(...);
          }
          
          -repackageclasses
          -allowaccessmodification
          -optimizationpasses 5
          PROGUARDEOF

      - name: Corrigir MainApplication.kt
        script: |
          cd "$WORKING_DIRECTORY"
          cat > android/app/src/main/java/com/nexa/cbox/MainApplication.kt <<'EOFKOTLIN'
          package com.nexa.cbox
          
          import android.app.Application
          import android.content.res.Configuration
          import expo.modules.ApplicationLifecycleDispatcher
          import expo.modules.ReactNativeHostWrapper
          import com.facebook.react.PackageList
          import com.facebook.react.ReactApplication
          import com.facebook.react.ReactNativeHost
          import com.facebook.react.ReactPackage
          import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.load
          import com.facebook.react.defaults.DefaultReactNativeHost
          import com.facebook.soloader.SoLoader
          import java.util.Locale
          
          class MainApplication : Application(), ReactApplication {
            override val reactNativeHost: ReactNativeHost = ReactNativeHostWrapper(
              this,
              object : DefaultReactNativeHost(this) {
                override fun getPackages(): List<ReactPackage> {
                  val packages = PackageList(this).packages
                  return packages
                }
          
                override fun getJSMainModuleName(): String = ".expo/.virtual-metro-entry"
          
                override fun getUseDeveloperSupport(): Boolean = false
          
                override val isNewArchEnabled: Boolean = false
                override val isHermesEnabled: Boolean = true
              }
            )
          
            override fun onCreate() {
              super.onCreate()
              SoLoader.init(this, false)
              load()
              ApplicationLifecycleDispatcher.onApplicationCreate(this)
            }
          
            override fun onConfigurationChanged(newConfig: Configuration) {
              super.onConfigurationChanged(newConfig)
              ApplicationLifecycleDispatcher.onConfigurationChanged(this, newConfig)
            }
          }
          EOFKOTLIN
          echo "MainApplication.kt substituído"

      - name: Build APK otimizado
        script: |
          cd "$WORKING_DIRECTORY/android"
          chmod +x ./gradlew
          ./gradlew clean
          ./gradlew assembleRelease --no-daemon -Dorg.gradle.jvmargs="-Xmx4096m"

      - name: Verificar tamanho e copiar APK
        script: |
          cd "$WORKING_DIRECTORY"
          echo "==> APKs gerados:"
          ls -lh android/app/build/outputs/apk/release/*.apk
          
          APK_PATH=$(find android/app/build/outputs/apk/release -name "*.apk" -type f | head -1)
          if [ -z "$APK_PATH" ]; then
            echo "Erro: Nenhum APK encontrado!"
            exit 1
          fi
          
          mkdir -p "$CM_BUILD_DIR"
          cp "$APK_PATH" "$CM_BUILD_DIR/app-release.apk"
          
          echo "==> Tamanho final do APK:"
          du -h "$CM_BUILD_DIR/app-release.apk"

    artifacts:
      - $CM_BUILD_DIR/*.apk
    publishing:
      email:
        recipients:
          - seu-email@example.com
        notify:
          success: true
          failure: true