<p>workflows:
  react-native-android:
    name: Coin Box - Android Build
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      vars:
        PACKAGE_NAME: "com.nexa.cbox"
        BUILD_GRADLE_B64: "YXBwbHkgcGx1Z2luOiAiY29tLmFuZHJvaWQuYXBwbGljYXRpb24iCmFwcGx5IHBsdWdpbjogIm9yZy5qZXRicmFpbnMua290bGluLmFuZHJvaWQiCmFwcGx5IHBsdWdpbjogImNvbS5mYWNlYm9vay5yZWFjdCIKCmRlZiBwcm9qZWN0Um9vdCA9IHJvb3REaXIuZ2V0QWJzb2x1dGVGaWxlKCkuZ2V0UGFyZW50RmlsZSgpLmdldEFic29sdXRlUGF0aCgpCgpyZWFjdCB7CiAgICBlbnRyeUZpbGUgPSBmaWxlKFsibm9kZSIsICItZSIsICJyZXF1aXJlKCdleHBvL3NjcmlwdHMvcmVzb2x2ZUFwcEVudHJ5JykiLCBwcm9qZWN0Um9vdCwgImFuZHJvaWQiLCAiYWJzb2x1dGUiXS5leGVjdXRlKG51bGwsIHJvb3REaXIpLnRleHQudHJpbSgpKQogICAgcmVhY3ROYXRpdmVEaXIgPSBuZXcgRmlsZShbIm5vZGUiLCAiLS1wcmludCIsICJyZXF1aXJlLnJlc29sdmUoJ3JlYWN0LW5hdGl2ZS9wYWNrYWdlLmpzb24nKSJdLmV4ZWN1dGUobnVsbCwgcm9vdERpcikudGV4dC50cmltKCkpLmdldFBhcmVudEZpbGUoKS5nZXRBYnNvbHV0ZUZpbGUoKQogICAgaGVybWVzQ29tbWFuZCA9IG5ldyBGaWxlKFsibm9kZSIsICItLXByaW50IiwgInJlcXVpcmUucmVzb2x2ZSgncmVhY3QtbmF0aXZlL3BhY2thZ2UuanNvbicpIl0uZXhlY3V0ZShudWxsLCByb290RGlyKS50ZXh0LnRyaW0oKSkuZ2V0UGFyZW50RmlsZSgpLmdldEFic29sdXRlUGF0aCgpICsgIi9zZGtzL2hlcm1lc2MvJU9TLUJJTiUvaGVybWVzYyIKICAgIGNvZGVnZW5EaXIgPSBuZXcgRmlsZShbIm5vZGUiLCAiLS1wcmludCIsICJyZXF1aXJlLnJlc29sdmUoJ0ByZWFjdC1uYXRpdmUvY29kZWdlbi9wYWNrYWdlLmpzb24nLCB7IHBhdGhzOiBbcmVxdWlyZS5yZXNvbHZlKCdyZWFjdC1uYXRpdmUvcGFja2FnZS5qc29uJyldIH0pIl0uZXhlY3V0ZShudWxsLCByb290RGlyKS50ZXh0LnRyaW0oKSkuZ2V0UGFyZW50RmlsZSgpLmdldEFic29sdXRlRmlsZSgpCiAgICBlbmFibGVCdW5kbGVDb21wcmVzc2lvbiA9IHRydWUKICAgIGNsaUZpbGUgPSBuZXcgRmlsZShbIm5vZGUiLCAiLS1wcmludCIsICJyZXF1aXJlLnJlc29sdmUoJ0BleHBvL2NsaScsIHsgcGF0aHM6IFtyZXF1aXJlLnJlc29sdmUoJ2V4cG8vcGFja2FnZS5qc29uJyldIH0pIl0uZXhlY3V0ZShudWxsLCByb290RGlyKS50ZXh0LnRyaW0oKSkKICAgIGJ1bmRsZUNvbW1hbmQgPSAiZXhwb3J0OmVtYmVkIgogICAgYXV0b2xpbmtMaWJyYXJpZXNXaXRoQXBwKCkKfQoKYW5kcm9pZCB7CiAgICBuZGtWZXJzaW9uIHJvb3RQcm9qZWN0LmV4dC5uZGtWZXJzaW9uCiAgICBidWlsZFRvb2xzVmVyc2lvbiByb290UHJvamVjdC5leHQuYnVpbGRUb29sc1ZlcnNpb24KICAgIGNvbXBpbGVTZGsgcm9vdFByb2plY3QuZXh0LmNvbXBpbGVTZGtWZXJzaW9uCiAgICBuYW1lc3BhY2UgImNvbS5uZXhhLmNib3giCgogICAgZGVmYXVsdENvbmZpZyB7CiAgICAgICAgYXBwbGljYXRpb25JZCAiY29tLm5leGEuY2JveCIKICAgICAgICBtaW5TZGsgMjQKICAgICAgICB0YXJnZXRTZGsgcm9vdFByb2plY3QuZXh0LnRhcmdldFNka1ZlcnNpb24KICAgICAgICB2ZXJzaW9uQ29kZSAxCiAgICAgICAgdmVyc2lvbk5hbWUgIjEuMCIKICAgICAgICBuZGsgewogICAgICAgICAgICBhYmlGaWx0ZXJzICJhcm02NC12OGEiCiAgICAgICAgfQogICAgICAgIGJ1aWxkQ29uZmlnRmllbGQgIlN0cmluZyIsICJSRUFDVF9OQVRJVkVfUkVMRUFTRV9MRVZFTCIsICJcInN0YWJsZVwiIgogICAgfQoKICAgIHNpZ25pbmdDb25maWdzIHsKICAgICAgICBkZWJ1ZyB7CiAgICAgICAgICAgIHN0b3JlRmlsZSBmaWxlKCdkZWJ1Zy5rZXlzdG9yZScpCiAgICAgICAgICAgIHN0b3JlUGFzc3dvcmQgJ2FuZHJvaWQnCiAgICAgICAgICAgIGtleUFsaWFzICdhbmRyb2lkZGVidWdrZXknCiAgICAgICAgICAgIGtleVBhc3N3b3JkICdhbmRyb2lkJwogICAgICAgIH0KICAgIH0KCiAgICBidWlsZFR5cGVzIHsKICAgICAgICByZWxlYXNlIHsKICAgICAgICAgICAgc2lnbmluZ0NvbmZpZyBzaWduaW5nQ29uZmlncy5kZWJ1ZwogICAgICAgICAgICBtaW5pZnlFbmFibGVkIHRydWUKICAgICAgICAgICAgc2hyaW5rUmVzb3VyY2VzIHRydWUKICAgICAgICAgICAgcHJvZ3VhcmRGaWxlcyBnZXREZWZhdWx0UHJvZ3VhcmRGaWxlKCJwcm9ndWFyZC1hbmRyb2lkLW9wdGltaXplLnR4dCIpLCAicHJvZ3VhcmQtcnVsZXMucHJvIgogICAgICAgIH0KICAgIH0KCiAgICBwYWNrYWdpbmdPcHRpb25zIHsKICAgICAgICBqbmlMaWJzIHsKICAgICAgICAgICAgdXNlTGVnYWN5UGFja2FnaW5nIGZhbHNlCiAgICAgICAgfQogICAgICAgIGV4Y2x1ZGUgJ01FVEEtSU5GLyoqJwogICAgICAgIGV4Y2x1ZGUgJyoqLyoua290bGluX21vZHVsZScKICAgICAgICBwaWNrRmlyc3QgJ2xpYi8qL2xpYmMrK19zaGFyZWQuc28nCiAgICB9Cn0KCmRlcGVuZGVuY2llcyB7CiAgICBpbXBsZW1lbnRhdGlvbigiY29tLmZhY2Vib29rLnJlYWN0OnJlYWN0LWFuZHJvaWQiKQogICAgaW1wbGVtZW50YXRpb24oImNvbS5mYWNlYm9vay5yZWFjdDpoZXJtZXMtYW5kcm9pZCIpCn0K"

    scripts:
      - name: Install npm dependencies
        script: |
          cd coin-box
          npm install

      - name: Run Expo Prebuild
        script: |
          cd coin-box
          npx expo prebuild --clean --platform android

      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/coin-box/android/local.properties"

      - name: Write build.gradle
        script: |
          echo "$BUILD_GRADLE_B64" | base64 -d > "$CM_BUILD_DIR/coin-box/android/app/build.gradle"

      - name: Build Android APK
        script: |
          cd coin-box/android
          ./gradlew assembleRelease --no-daemon

    artifacts:
      - coin-box/android/app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - seu-email@exemplo.com
        notify:
          success: true
          failure: true</p>
