format_version: "11"

app:
  envs:
    - WORKING_DIRECTORY: "coin-box"

workflows:
  react-native-android-minimal-apk:
    max_build_duration: 60
    steps:
      - git-clone: {}
      - cache-pull: {}

      - script:
          title: Install dependencies
          inputs:
            - content: |
                #!/bin/bash
                set -euo pipefail
                echo "==> Install node deps"
                cd "$WORKING_DIRECTORY"
                if [ -f package-lock.json ]; then
                  npm ci
                else
                  npm install --no-audit --no-fund
                fi

      - script:
          title: Expo prebuild (android) - create native project
          inputs:
            - content: |
                #!/bin/bash
                set -euo pipefail
                echo "==> Running expo prebuild (clean android folder)"
                cd "$WORKING_DIRECTORY"
                rm -rf android
                npx expo prebuild --platform android --clean

      - script:
          title: Force aggressive Android optimizations (Hermes, R8, shrink, single ABI)
          inputs:
            - content: |
                #!/bin/bash
                set -euo pipefail
                echo "==> Applying aggressive optimizations to reduce APK size"

                ROOT="$PWD/$WORKING_DIRECTORY/android"
                APP_BUILD="$ROOT/app/build.gradle"
                GRADLE_PROPS="$ROOT/gradle.properties"
                PROGUARD="$ROOT/app/proguard-rules.pro"

                # Backup original files (safe)
                cp "$APP_BUILD" "$APP_BUILD.bak" 2>/dev/null || true
                cp "$GRADLE_PROPS" "$GRADLE_PROPS.bak" 2>/dev/null || true

                # 1) Enable Hermes in gradle.properties or project.ext (best-effort)
                if ! grep -q "enableHermes" "$APP_BUILD"; then
                  echo "-> Adding project.ext.react = [ enableHermes: true ] to android/build.gradle (best-effort)"
                  awk 'BEGIN{printed=0}
                    /buildscript/ && printed==0 {
                      print;
                      print "project.ext.react = [ enableHermes: true ]";
                      printed=1;
                      next
                    }
                    {print}
                  ' "$APP_BUILD" > "$APP_BUILD.tmp" && mv "$APP_BUILD.tmp" "$APP_BUILD" || true
                else
                  echo "-> Hermes already configured"
                fi

                # 2) Turn on minifyEnabled and shrinkResources in release block (conservative edits)
                sed -E -i.bak -e '/release[[:space:]]*\\{/,/\\}/{
                  s/minifyEnabled[[:space:]]*false/minifyEnabled true/g
                  s/shrinkResources[[:space:]]*false/shrinkResources true/g
                }' "$APP_BUILD" || true

                # If minify/shrink not present, insert them after the "release {" line
                if ! sed -n '/release[[:space:]]*{/,/}/p' "$APP_BUILD" | grep -q "minifyEnabled"; then
                  awk '{
                    print
                    if ($0 ~ /release[[:space:]]*{/) {
                      print "            minifyEnabled true"
                      print "            shrinkResources true"
                    }
                  }' "$APP_BUILD" > "$APP_BUILD.tmp" && mv "$APP_BUILD.tmp" "$APP_BUILD" || true
                fi

                # 3) Ensure proguardFiles reference exists in release
                if ! sed -n '/release[[:space:]]*{/,/}/p' "$APP_BUILD" | grep -q "proguardFiles"; then
                  sed -E -i.bak '/release[[:space:]]*\{/,/\}/ s/\}/    proguardFiles getDefaultProguardFile('\''proguard-android-optimize.txt'\''); proguardFiles getDefaultProguardFile('\''proguard-android-optimize.txt'\'') \n  \}/' "$APP_BUILD" 2>/dev/null || true
                  # fallback conservative insertion
                  sed -i.bak '/release[[:space:]]*{/a \ \ \ \ proguardFiles getDefaultProguardFile('\''proguard-android-optimize.txt'\'') , '\''proguard-rules.pro'\'' ' "$APP_BUILD" 2>/dev/null || true
                fi

                # 4) Force single ABI (armeabi-v7a) to drastically cut native libs size
                if ! sed -n '/defaultConfig[[:space:]]*{/,/}/p' "$APP_BUILD" | grep -q "abiFilters"; then
                  awk '{
                    print
                    if ($0 ~ /defaultConfig[[:space:]]*{/) {
                      print "        ndk {"
                      print "            abiFilters \"armeabi-v7a\""
                      print "        }"
                    }
                  }' "$APP_BUILD" > "$APP_BUILD.tmp" && mv "$APP_BUILD.tmp" "$APP_BUILD" || true
                fi

                # 5) gradle.properties tweaks
                if ! grep -q "org.gradle.jvmargs" "$GRADLE_PROPS"; then
                  echo "org.gradle.jvmargs=-Xmx4608m" >> "$GRADLE_PROPS"
                else
                  sed -i.bak 's/^org.gradle.jvmargs=.*/org.gradle.jvmargs=-Xmx4608m/' "$GRADLE_PROPS" || true
                fi
                if ! grep -q "android.enableR8" "$GRADLE_PROPS"; then
                  echo "android.enableR8=true" >> "$GRADLE_PROPS"
                fi

                # 6) Create minimal proguard rules using a HEREDOC — note the single quotes around EOF:
                #     these lines start with '-' and must be inside the script block scalar to avoid YAML parse errors.
                cat > "$PROGUARD" <<'EOF'
-keep class com.facebook.react.** { *; }
-keep class com.facebook.hermes.** { *; }
-dontwarn com.facebook.react.**
-dontwarn okhttp3.**
-dontwarn okio.**
-keepclassmembers class * { @com.facebook.react.uimanager.annotations.ReactProp *; }
EOF

                echo "Optimizations applied. Review android/app/build.gradle if you need other custom keep rules."

      - script:
          title: Build RELEASE APK (single-ABI, optimized)
          inputs:
            - content: |
                #!/bin/bash
                set -euo pipefail
                echo "==> Building optimized RELEASE APK (single ABI)"
                cd "$WORKING_DIRECTORY/android"
                chmod +x ./gradlew
                ./gradlew clean
                ./gradlew assembleRelease --no-daemon

                echo "==> Locating generated APKs..."
                APKS=$(find app/build/outputs -type f -name "*.apk" 2>/dev/null || true)
                if [ -z "$APKS" ]; then
                  echo "No APK files found under app/build/outputs — build probably failed."
                  exit 1
                fi

                SMALLEST_APK=$(for f in $APKS; do echo "$(stat -c%s "$f"):$f"; done | sort -n | head -n1 | cut -d: -f2-)
                SMALLEST_SIZE=$(stat -c%s "$SMALLEST_APK" || true)

                mkdir -p "$BITRISE_DEPLOY_DIR"
                cp "$SMALLEST_APK" "$BITRISE_DEPLOY_DIR/app-release.apk"

                echo "Final APK size: $((SMALLEST_SIZE/1024)) KB (~$((SMALLEST_SIZE/1024/1024)) MB)"

      - cache-push: {}
      - deploy-to-bitrise-io: {}