workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 60
    environment:
      node: latest
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          cd coin-box
          npm install
      
      - name: Set up Android keystore (opcional)
        script: |
          # Se tiveres keystore configurado, descomenta estas linhas
          # echo $ANDROID_KEYSTORE | base64 --decode > /tmp/keystore.jks
          # export ANDROID_KEYSTORE_PATH=/tmp/keystore.jks
      
      - name: Build Android APK
        script: |
          cd coin-box/android
          ./gradlew assembleRelease
    
    artifacts:
      - coin-box/android/app/build/outputs/**/*.apk
    
    publishing:
      email:
        recipients:
          - seu-email@example.com  # Substitui pelo teu email
        notify:
          success: true
          failure: true

  react-native-ios:
    name: React Native iOS
    max_build_duration: 60
    environment:
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          cd coin-box
          npm install
      
      - name: Install CocoaPods dependencies
        script: |
          cd coin-box/ios
          pod install
      
      - name: Build iOS
        script: |
          cd coin-box/ios
          xcodebuild -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/Runner.xcarchive \
            archive
    
    artifacts:
      - coin-box/ios/build/**/*.ipa
    
    publishing:
      email:
        recipients:
          - seu-email@example.com  # Substitui pelo teu email
        notify:
          success: true
          failure: true