workflows:
  android-build:
    name: Android APK
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        WORKING_DIRECTORY: "coin-box"
      node: 20.11.0
      java: 17
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $WORKING_DIRECTORY/node_modules
    scripts:
      - name: Install dependencies
        script: |
          cd "$WORKING_DIRECTORY"
          
          # Limpar cache do npm
          npm cache clean --force
          
          # Instalar dependências
          npm install
          
          # Instalar plugins Babel necessários
          npm install --save-dev @babel/plugin-proposal-private-property-in-object
          npm install --save-dev @babel/plugin-transform-private-property-in-object
          
          echo "✅ Dependências instaladas"

      - name: Fix Babel config
        script: |
          cd "$WORKING_DIRECTORY"
          
          # Criar/atualizar babel.config.js com plugin necessário
          cat > babel.config.js << 'BABELCONFIG'
          module.exports = function(api) {
            api.cache(true);
            return {
              presets: ['babel-preset-expo'],
              plugins: [
                ['@babel/plugin-proposal-private-property-in-object', { loose: true }],
                ['@babel/plugin-transform-private-property-in-object', { loose: true }]
              ]
            };
          };
          BABELCONFIG
          
          echo "✅ Babel configurado"

      - name: Expo prebuild
        script: |
          cd "$WORKING_DIRECTORY"
          
          # Remover android existente
          rm -rf android
          
          # Limpar cache do Metro
          npx expo start --clear
          
          # Prebuild
          npx expo prebuild --platform android --clean
          
          echo "✅ Prebuild completo"

      - name: Configure build
        script: |
          cd "$WORKING_DIRECTORY/android"
          
          # Configurar gradle.properties
          echo "" >> gradle.properties
          echo "org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=1g" >> gradle.properties
          echo "org.gradle.parallel=true" >> gradle.properties
          echo "org.gradle.daemon=false" >> gradle.properties
          echo "android.enableJetifier=true" >> gradle.properties
          echo "android.useAndroidX=true" >> gradle.properties
          echo "reactNativeArchitectures=arm64-v8a" >> gradle.properties
          
          # Metro bundler config
          echo "hermesEnabled=true" >> gradle.properties
          
          # Configurar build.gradle do app
          cd app
          
          # Script para fix do build.gradle
          cat > /tmp/fix_build.sh << 'FIXSCRIPT'
          #!/bin/bash
          
          # Desabilitar minify
          sed -i.bak 's/minifyEnabled true/minifyEnabled false/g' build.gradle
          sed -i.bak 's/shrinkResources true/shrinkResources false/g' build.gradle
          
          # Adicionar signingConfig se não existir
          if ! grep -q "signingConfig signingConfigs.debug" build.gradle; then
            sed -i.bak '/release {/a\
                signingConfig signingConfigs.debug
          ' build.gradle
          fi
          
          echo "✓ build.gradle configurado"
          FIXSCRIPT
          
          chmod +x /tmp/fix_build.sh
          /tmp/fix_build.sh
          
          echo "=== Release config ==="
          grep -A 10 "release {" build.gradle || echo "Não encontrado"

      - name: Build APK
        script: |
          set -e
          
          cd "$WORKING_DIRECTORY/android"
          
          echo "🚀 Iniciando build do APK..."
          
          # Limpar build anterior
          ./gradlew clean --no-daemon --quiet
          
          # Build com melhor handling de erros
          if ./gradlew assembleRelease \
            --no-daemon \
            --stacktrace \
            --warning-mode all 2>&1 | tee /tmp/build.log; then
            echo "✅ Build completo!"
          else
            echo ""
            echo "❌ BUILD FALHOU!"
            echo ""
            echo "=== ÚLTIMAS 100 LINHAS DO LOG ==="
            tail -100 /tmp/build.log
            echo ""
            
            # Verificar erros específicos
            if grep -q "Execution failed for task" /tmp/build.log; then
              echo "=== ERRO DE TASK GRADLE ==="
              grep -A 20 "Execution failed for task" /tmp/build.log
            fi
            
            if grep -q "FAILURE: Build failed" /tmp/build.log; then
              echo "=== DETALHES DO ERRO ==="
              grep -A 30 "FAILURE: Build failed" /tmp/build.log
            fi
            
            if grep -q "Unable to load script" /tmp/build.log; then
              echo "=== ERRO DE BUNDLE JS ==="
              grep -B 5 -A 20 "Unable to load script" /tmp/build.log
            fi
            
            echo ""
            exit 1
          fi

      - name: Copy APK
        script: |
          set -e
          set -x
          
          cd "$WORKING_DIRECTORY"
          
          echo "=========================================="
          echo "PROCURANDO APK"
          echo "=========================================="
          
          # Mostrar toda estrutura de outputs
          find android/app/build/outputs -name "*.apk" -type f || echo "Nenhum APK encontrado"
          
          # Tentar encontrar APK
          APK_PATH=$(find android/app/build/outputs/apk/release -name "*.apk" -type f | head -1)
          
          if [ -z "$APK_PATH" ]; then
            echo ""
            echo "❌ NENHUM APK ENCONTRADO!"
            echo ""
            echo "Estrutura completa de build/outputs:"
            ls -R android/app/build/outputs/ || echo "Diretório não existe"
            echo ""
            echo "Estrutura de android/app/build:"
            ls -R android/app/build/ || echo "Diretório não existe"
            exit 1
          fi
          
          echo ""
          echo "✅ APK encontrado: $APK_PATH"
          echo ""
          
          # Criar diretório e copiar
          mkdir -p "$CM_BUILD_DIR"
          cp "$APK_PATH" "$CM_BUILD_DIR/coin-box.apk"
          
          echo "=========================================="
          echo "APK COPIADO COM SUCESSO"
          echo "=========================================="
          ls -lh "$CM_BUILD_DIR/coin-box.apk"
          echo ""
          echo "Tamanho: $(du -h "$CM_BUILD_DIR/coin-box.apk" | cut -f1)"
          echo ""

    artifacts:
      - $CM_BUILD_DIR/*.apk

    publishing:
      email:
        recipients:
          - alfredoooh.x3@gmail.com
        notify:
          success: true
          failure: true
