workflows:
  react-native-android:
    name: Coin Box - Android Build
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      vars:
        PACKAGE_NAME: "com.nexa.cbox"

    scripts:
      - name: Install npm dependencies
        script: |
          cd coin-box
          npm install

      - name: Run Expo Prebuild
        script: |
          cd coin-box
          npx expo prebuild --clean --platform android

      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/coin-box/android/local.properties"

      - name: Copy build.gradle
        script: |
          cp "$CM_BUILD_DIR/coin-box/android/app/build.gradle.orig" "$CM_BUILD_DIR/coin-box/android/app/build.gradle"

      - name: Build Android APK
        script: |
          cd coin-box/android
          ./gradlew assembleRelease --no-daemon

    artifacts:
      - coin-box/android/app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - seu-email@exemplo.com
        notify:
          success: true
          failure: true
