workflows:
  react-native-android:
    name: Coin Box - Android Build
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      vars:
        PACKAGE_NAME: "com.nexa.cbox"

    scripts:
      - name: Install npm dependencies
        script: |
          cd coin-box
          npm install

      - name: Run Expo Prebuild
        script: |
          cd coin-box
          npx expo prebuild --clean --platform android

      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/coin-box/android/local.properties"

      - name: Write build.gradle
        script: |
          cat > $CM_BUILD_DIR/coin-box/android/app/build.gradle \<< 'EOF'
          apply plugin: "com.android.application"
          apply plugin: "org.jetbrains.kotlin.android"
          apply plugin: "com.facebook.react"
          def projectRoot = rootDir.getAbsoluteFile().getParentFile().getAbsolutePath()
          react {
            autolinkLibrariesWithApp()
            enableBundleCompression = true
            bundleCommand = "export:embed"
          }
          android {
            ndkVersion rootProject.ext.ndkVersion
            buildToolsVersion rootProject.ext.buildToolsVersion
            compileSdk rootProject.ext.compileSdkVersion
            namespace "com.nexa.cbox"
            defaultConfig {
              applicationId "com.nexa.cbox"
              minSdk 24
              targetSdk rootProject.ext.targetSdkVersion
              versionCode 1
              versionName "1.0"
              ndk { abiFilters "arm64-v8a" }
            }
            signingConfigs {
              debug {
                storeFile file('debug.keystore')
                storePassword 'android'
                keyAlias 'androiddebugkey'
                keyPassword 'android'
              }
            }
            buildTypes {
              release {
                signingConfig signingConfigs.debug
                minifyEnabled true
                shrinkResources true
                proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
              }
            }
          }
          dependencies {
            implementation("com.facebook.react:react-android")
            implementation("com.facebook.react:hermes-android")
          }
          EOF

      - name: Build Android APK
        script: |
          cd coin-box/android
          ./gradlew assembleRelease --no-daemon

    artifacts:
      - coin-box/android/app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - seu-email@exemplo.com
        notify:
          success: true
          failure: true
