workflows:
  android-build:
    name: Android APK
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        WORKING_DIRECTORY: "coin-box"
      node: 20.11.0
      java: 17
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $WORKING_DIRECTORY/node_modules
    scripts:
      - name: Install dependencies
        script: |
          cd "$WORKING_DIRECTORY"
          npm install

      - name: Expo prebuild
        script: |
          cd "$WORKING_DIRECTORY"
          rm -rf android
          npx expo prebuild --platform android --clean

      - name: Configure build
        script: |
          cd "$WORKING_DIRECTORY/android"
          
          # Configurar gradle.properties
          echo "" >> gradle.properties
          echo "org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=1g" >> gradle.properties
          echo "org.gradle.parallel=true" >> gradle.properties
          echo "org.gradle.daemon=false" >> gradle.properties
          echo "android.enableJetifier=true" >> gradle.properties
          echo "android.useAndroidX=true" >> gradle.properties
          echo "reactNativeArchitectures=arm64-v8a" >> gradle.properties
          
          # Desabilitar minify no build.gradle
          cd app
          sed -i.bak 's/minifyEnabled true/minifyEnabled false/' build.gradle
          sed -i.bak 's/shrinkResources true/shrinkResources false/' build.gradle
          
          echo "=== Config aplicada ==="
          grep -A 5 "minifyEnabled" build.gradle

      - name: Build APK
        script: |
          cd "$WORKING_DIRECTORY/android"
          ./gradlew clean assembleRelease --stacktrace --no-daemon

      - name: Copy APK
        script: |
          cd "$WORKING_DIRECTORY"
          mkdir -p "$CM_BUILD_DIR"
          cp android/app/build/outputs/apk/release/*.apk "$CM_BUILD_DIR/coin-box.apk"
          ls -lh "$CM_BUILD_DIR/coin-box.apk"

    artifacts:
      - $CM_BUILD_DIR/*.apk
      
    publishing:
      email:
        recipients:
          - alfredoooh.x3@gmail.com
        notify:
          success: true
          failure: true
