workflows:
  expo-webview:
    name: Expo WebView Otimizado
    environment:
      node: latest
    scripts:
      - name: Install
        script: npm install
        
      - name: Prebuild
        script: npx expo prebuild --platform android --clean
        
      - name: Otimizar build.gradle
        script: |
          cat > android/app/build.gradle <<'EOF'
          apply plugin: "com.android.application"
          apply plugin: "org.jetbrains.kotlin.android"
          apply plugin: "com.facebook.react"

          react {
              cliFile = new File(["node", "--print", "require.resolve('@expo/cli')"].execute(null, rootDir).text.trim())
          }

          android {
              namespace "com.nexa.cbox"
              compileSdk 34
              
              defaultConfig {
                  applicationId "com.nexa.cbox"
                  minSdk 24
                  targetSdk 34
                  versionCode 1
                  versionName "1.0"
              }
              
              buildTypes {
                  release {
                      minifyEnabled true
                      shrinkResources true
                      proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
                  }
              }
              
              splits {
                  abi {
                      enable true
                      reset()
                      include 'arm64-v8a'
                      universalApk false
                  }
              }
              
              packagingOptions {
                  resources {
                      excludes += ['META-INF/**', 'kotlin/**']
                  }
              }
          }

          dependencies {
              implementation("com.facebook.react:react-android")
              implementation("com.facebook.react:hermes-android")
          }
          EOF
          
      - name: Build APK
        script: cd android && ./gradlew assembleRelease --no-daemon
        
    artifacts:
      - android/app/build/outputs/apk/release/*.apk