format_version: "11"

app:
  envs:
    - WORKING_DIRECTORY: "coin-box"

workflows:
  react-native-android-minimal-apk:
    max_build_duration: 60
    steps:
      - git-clone: {}
      - cache-pull: {}

      - script:
          title: Install dependencies
          inputs:
            - content: |
                #!/bin/bash
                set -euo pipefail
                echo "==> Install node deps"
                cd "$WORKING_DIRECTORY"
                if [ -f package-lock.json ]; then
                  npm ci
                else
                  npm install --no-audit --no-fund
                fi

      - script:
          title: Expo prebuild (android) - create native project
          inputs:
            - content: |
                #!/bin/bash
                set -euo pipefail
                echo "==> Running expo prebuild (clean android folder)"
                cd "$WORKING_DIRECTORY"
                rm -rf android
                # Ensure expo-cli available for prebuild (npx will download if needed)
                npx expo prebuild --platform android --clean

      - script:
          title: Force aggressive Android optimizations (Hermes, R8, shrink, single ABI)
          inputs:
            - content: |
                #!/bin/bash
                set -euo pipefail
                echo "==> Applying aggressive optimizations to reduce APK size"

                ROOT="$PWD/$WORKING_DIRECTORY/android"
                APP_BUILD="$ROOT/app/build.gradle"
                GRADLE_PROPS="$ROOT/gradle.properties"
                PROGUARD="$ROOT/app/proguard-rules.pro"

                # Backup original files (safe)
                cp "$APP_BUILD" "$APP_BUILD.bak" 2>/dev/null || true
                cp "$GRADLE_PROPS" "$GRADLE_PROPS.bak" 2>/dev/null || true

                # 1) Enable Hermes (if React Native gradle config style used)
                # Insert project.ext.react = [ enableHermes: true ] near top if not present
                if ! grep -q "enableHermes" "$APP_BUILD"; then
                  echo "-> Enabling Hermes in build.gradle (project.ext.react)"
                  awk 'BEGIN{printed=0}
                    /buildscript/ && printed==0 {
                      print;
                      print "project.ext.react = [ enableHermes: true ]";
                      printed=1;
                      next
                    }
                    {print}
                  ' "$APP_BUILD" > "$APP_BUILD.tmp" && mv "$APP_BUILD.tmp" "$APP_BUILD" || true
                else
                  echo "-> Hermes already configured in build.gradle"
                fi

                # 2) Ensure release buildType has minifyEnabled true and shrinkResources true
                if grep -q "buildTypes" "$APP_BUILD"; then
                  echo "-> Turning on minifyEnabled and shrinkResources in release block"
                  # Set minifyEnabled true and shrinkResources true if false or missing
                  sed -E -i.bak -e '/release[[:space:]]*\{/,/\}/{
                    s/minifyEnabled[[:space:]]*false/minifyEnabled true/g
                    s/shrinkResources[[:space:]]*false/shrinkResources true/g
                  }' "$APP_BUILD" || true

                  # If keys not present, add them directly after "release {"
                  if ! sed -n '/release[[:space:]]*{/,/\}/p' "$APP_BUILD" | grep -q "minifyEnabled"; then
                    awk '{
                      print
                      if ($0 ~ /release[[:space:]]*{/) {
                        print "            minifyEnabled true"
                        print "            shrinkResources true"
                      }
                    }' "$APP_BUILD" > "$APP_BUILD.tmp" && mv "$APP_BUILD.tmp" "$APP_BUILD" || true
                  fi
                fi

                # 3) Ensure proguard files are referenced in release
                if ! sed -n '/release[[:space:]]*{/,/\}/p' "$APP_BUILD" | grep -q "proguardFiles"; then
                  echo "-> Adding proguardFiles to release buildType"
                  sed -E -i.bak '/release[[:space:]]*\{/,/\}/ s/\}/    proguardFiles getDefaultProguardFile('"'"'proguard-android-optimize.txt'"'"'), '"'"'proguard-rules.pro'"'"'\n  \}/' "$APP_BUILD" || true
                fi

                # 4) Force single ABI (armeabi-v7a) to drastically cut native libs size
                # Place ndk.abiFilters in defaultConfig if not present
                if ! sed -n '/defaultConfig[[:space:]]*{/,/\}/p' "$APP_BUILD" | grep -q "abiFilters"; then
                  echo "-> Forcing single ABI (armeabi-v7a) in defaultConfig"
                  awk '{
                    print
                    if ($0 ~ /defaultConfig[[:space:]]*{/) {
                      print "        ndk {"
                      print "            abiFilters \"armeabi-v7a\""
                      print "        }"
                    }
                  }' "$APP_BUILD" > "$APP_BUILD.tmp" && mv "$APP_BUILD.tmp" "$APP_BUILD" || true
                fi

                # 5) gradle.properties tweaks: increase heap, ensure R8 enabled, disable debug symbols packaging
                if ! grep -q "org.gradle.jvmargs" "$GRADLE_PROPS"; then
                  echo "org.gradle.jvmargs=-Xmx4608m" >> "$GRADLE_PROPS"
                else
                  sed -i.bak 's/^org.gradle.jvmargs=.*/org.gradle.jvmargs=-Xmx4608m/' "$GRADLE_PROPS" || true
                fi
                if ! grep -q "android.enableR8" "$GRADLE_PROPS"; then
                  echo "android.enableR8=true" >> "$GRADLE_PROPS"
                fi
                # Disable generation of debug symbols packaging if present (best-effort)
                if ! grep -q "android.debug.obsoleteApi" "$GRADLE_PROPS"; then
                  echo "android.debug.obsoleteApi=false" >> "$GRADLE_PROPS"
                fi

                # 6) Minimal proguard rules to allow shrinking (you can extend if you need to keep things)
                cat > "$PROGUARD" <<'EOF'
# Minimal proguard-rules.pro for React Native + Hermes
-keep class com.facebook.react.** { *; }
-keep class com.facebook.hermes.** { *; }
-dontwarn com.facebook.react.**
-dontwarn okhttp3.**
-dontwarn okio.**
# Keep RN callbacks
-keepclassmembers class * { @com.facebook.react.uimanager.annotations.ReactProp *; }
EOF

                echo "Optimizations applied. Review android/app/build.gradle if you need other custom keep rules."

      - script:
          title: Build RELEASE APK (single-ABI, optimized)
          inputs:
            - content: |
                #!/bin/bash
                set -euo pipefail
                echo "==> Building optimized RELEASE APK (single ABI)"
                cd "$WORKING_DIRECTORY/android"
                chmod +x ./gradlew
                ./gradlew clean

                # Assemble release (will produce APK for the forced ABI only)
                ./gradlew assembleRelease --no-daemon

                # Collect APKs and pick the smallest one (likely the single-ABI release)
                echo "==> Locating generated APKs..."
                APKS=$(find app/build/outputs -type f -name "*.apk" 2>/dev/null || true)

                if [ -z "$APKS" ]; then
                  echo "No APK files found under app/build/outputs — build probably failed."
                  exit 1
                fi

                # Choose smallest APK (size in bytes)
                SMALLEST_APK=$(for f in $APKS; do echo "$(stat -c%s "$f"):$f"; done | sort -n | head -n1 | cut -d: -f2-)
                SMALLEST_SIZE=$(stat -c%s "$SMALLEST_APK" || true)

                echo "Smallest APK: $SMALLEST_APK (size: ${SMALLEST_SIZE} bytes)"

                # Prepare deploy dir and copy chosen APK as app-release.apk
                mkdir -p "$BITRISE_DEPLOY_DIR"
                cp "$SMALLEST_APK" "$BITRISE_DEPLOY_DIR/app-release.apk"

                # Print final size in KB/MB
                echo "Final APK size: $((SMALLEST_SIZE/1024)) KB (~$((SMALLEST_SIZE/1024/1024)) MB)"

      - cache-push: {}
      - deploy-to-bitrise-io: {}